version: '3'

services:
  product-service:
    build: ./product
    volumes:
      - ./product/src:/usr/src/app
    ports:
      - 3000:3000
  website:
    build: ./website
    volumes:
      - ./website/src:/var/www/html
    ports:
      - 80:80
    depends_on:
      - product-service